/**
 * Dados demonstrativos (fictícios). Todos marcados com `is_demo: true` ou prefixo
 * "demo-" nos IDs para facilitar a remoção quando o Supabase for conectado.
 */
import type {
  Approval,
  AuditLog,
  Customer,
  Order,
  OrderFile,
  OrderItem,
  Printer,
  ProductionEvent,
  ProductionJob,
  TeamMember,
} from "./types";

const now = new Date();
const iso = (offsetDays: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() + offsetDays);
  d.setHours(12, 0, 0, 0);
  return d.toISOString();
};
const base = (offset = -20) => ({ created_at: iso(offset), updated_at: iso(-1), deleted_at: null });

export const demoCustomers: Customer[] = [
  {
    id: "demo-c1",
    name: "Marina Duarte",
    company: "Nortex Eventos (fictício)",
    phone: "(41) 99812-4477",
    email: "marina@nortex.demo",
    city: "Curitiba",
    state: "PR",
    notes: "Cliente demonstrativo. Pede sempre acabamento fosco.",
    ...base(-90),
  },
  {
    id: "demo-c2",
    name: "Ricardo Belmonte",
    company: "Belmonte Advocacia (fictício)",
    phone: "(11) 98123-7788",
    email: "ricardo@belmonte.demo",
    city: "São Paulo",
    state: "SP",
    notes: "Cliente demonstrativo.",
    ...base(-70),
  },
  {
    id: "demo-c3",
    name: "Aline Cordeiro",
    company: null,
    phone: "(48) 99655-1020",
    email: null,
    city: "Florianópolis",
    state: "SC",
    notes: "Cliente demonstrativo. Pet personalizado.",
    ...base(-45),
  },
  {
    id: "demo-c4",
    name: "Grupo Vertice (fictício)",
    company: "Vertice Indústria",
    phone: "(31) 98444-3300",
    email: "compras@vertice.demo",
    city: "Belo Horizonte",
    state: "MG",
    notes: "Cliente demonstrativo. Compras recorrentes de brindes.",
    ...base(-120),
  },
];

export const demoTeam: TeamMember[] = [
  {
    id: "demo-t1",
    name: "Renan Souza",
    avatar_url: null,
    job_title: "Modelagem 3D",
    role: "producao",
    phone: "(41) 99000-1111",
    email: "renan@gaeva.demo",
    active: true,
    capacity: 6,
    specialties: ["Modelagem orgânica", "Retopologia"],
    notes: "Demo",
    ...base(-200),
  },
  {
    id: "demo-t2",
    name: "Paula Nunes",
    avatar_url: null,
    job_title: "Operação de impressão",
    role: "producao",
    phone: "(41) 99000-2222",
    email: "paula@gaeva.demo",
    active: true,
    capacity: 8,
    specialties: ["Resina", "Acabamento"],
    notes: "Demo",
    ...base(-200),
  },
  {
    id: "demo-t3",
    name: "Caio Ferraz",
    avatar_url: null,
    job_title: "Comercial",
    role: "comercial",
    phone: "(41) 99000-3333",
    email: "caio@gaeva.demo",
    active: true,
    capacity: 12,
    specialties: ["Contas corporativas"],
    notes: "Demo",
    ...base(-200),
  },
  {
    id: "demo-t4",
    name: "Direção GAEVA",
    avatar_url: null,
    job_title: "Direção",
    role: "admin",
    phone: "(41) 99000-4444",
    email: "direcao@gaeva.demo",
    active: true,
    capacity: 20,
    specialties: ["Gestão"],
    notes: "Demo",
    ...base(-300),
  },
];

export const demoPrinters: Printer[] = [
  {
    id: "demo-p1",
    name: "Snapmaker U1",
    technology: "FDM multicor",
    status: "imprimindo",
    current_material: "PLA branco",
    current_order_id: "demo-o3",
    queue: ["demo-o5"],
    estimated_hours: 14,
    notes: "Máquina principal de peças grandes.",
    ...base(-300),
  },
  {
    id: "demo-p2",
    name: "Bambu Lab A1",
    technology: "FDM rápido",
    status: "disponivel",
    current_material: "PETG preto",
    current_order_id: null,
    queue: [],
    estimated_hours: null,
    notes: "Ideal para brindes em série.",
    ...base(-300),
  },
  {
    id: "demo-p3",
    name: "Elegoo Saturn 4 Ultra 12K",
    technology: "Resina LCD",
    status: "manutencao",
    current_material: "Resina cinza",
    current_order_id: null,
    queue: ["demo-o4"],
    estimated_hours: null,
    notes: "Troca de FEP agendada.",
    ...base(-300),
  },
];

const orderBase = {
  is_demo: true,
  briefing_complete: true,
  blocked_reason: null,
  urgency_reason: null,
  deleted_at: null,
};

export const demoOrders: Order[] = [
  {
    ...orderBase,
    id: "demo-o1",
    code: `GAE-${now.getFullYear()}-0001`,
    customer_id: "demo-c1",
    product: "mascote_corporativo",
    project_name: "Mascote Nortex 30cm",
    quantity: 2,
    dimensions: "30 x 18 x 18 cm",
    material: "PLA + pintura",
    colors: "Azul e branco",
    finishing: "Pintura fosca",
    purpose: "Feira corporativa",
    event_date: iso(5),
    due_date: iso(3),
    status: "em_modelagem",
    priority: "alta",
    owner_id: "demo-t1",
    printer_id: null,
    estimated_hours: 26,
    estimated_material: "1,2 kg PLA",
    internal_notes: "Cliente aprovou o conceito por WhatsApp.",
    commercial_notes: "Fechado com 50% de entrada.",
    briefing: "Mascote em pé, sorrindo, segurando placa com logotipo.",
    references_notes: "3 imagens de referência enviadas.",
    rights_notes: "Autorização de uso de marca enviada por e-mail.",
    value: 4800,
    down_payment: 2400,
    payment_status: "entrada_paga",
    approval_registered: false,
    approval_date: null,
    approval_version: "v1",
    approval_notes: null,
    created_at: iso(-14),
    updated_at: iso(-1),
  },
  {
    ...orderBase,
    id: "demo-o2",
    code: `GAE-${now.getFullYear()}-0002`,
    customer_id: "demo-c2",
    product: "trofeu",
    project_name: "Troféu Belmonte 2026",
    quantity: 12,
    dimensions: "22 cm",
    material: "Resina",
    colors: "Dourado",
    finishing: "Verniz brilhante",
    purpose: "Premiação interna",
    event_date: iso(2),
    due_date: iso(-2),
    status: "aguardando_aprovacao",
    priority: "urgente",
    urgency_reason: "Evento com data fixa e convites já enviados.",
    owner_id: "demo-t2",
    printer_id: null,
    estimated_hours: 18,
    estimated_material: "900 ml resina",
    internal_notes: "Aguardando retorno do cliente sobre a base.",
    commercial_notes: "Pagamento total na entrega.",
    briefing: "Troféu com base gravada e símbolo da balança.",
    references_notes: "Arte vetorial enviada.",
    rights_notes: "Logotipo cedido pelo cliente.",
    value: 7200,
    down_payment: 0,
    payment_status: "pendente",
    approval_registered: false,
    approval_date: null,
    approval_version: "v2",
    approval_notes: "Versão 2 enviada para avaliação.",
    created_at: iso(-21),
    updated_at: iso(-2),
  },
  {
    ...orderBase,
    id: "demo-o3",
    code: `GAE-${now.getFullYear()}-0003`,
    customer_id: "demo-c4",
    product: "chaveiro_corporativo",
    project_name: "Chaveiros Vertice",
    quantity: 250,
    dimensions: "5 cm",
    material: "PLA",
    colors: "Branco e vermelho",
    finishing: "Sem pintura",
    purpose: "Brinde de convenção",
    event_date: null,
    due_date: iso(6),
    status: "imprimindo",
    priority: "normal",
    owner_id: "demo-t2",
    printer_id: "demo-p1",
    estimated_hours: 40,
    estimated_material: "2,5 kg PLA",
    internal_notes: "Rodando em lotes de 50.",
    commercial_notes: "Contrato anual.",
    briefing: "Chaveiro com logotipo em relevo.",
    references_notes: "Arquivo STL aprovado.",
    rights_notes: "Marca própria do cliente.",
    value: 3750,
    down_payment: 3750,
    payment_status: "pago",
    approval_registered: true,
    approval_date: iso(-5),
    approval_version: "v1",
    approval_notes: "Aprovado por e-mail.",
    created_at: iso(-30),
    updated_at: iso(0),
  },
  {
    ...orderBase,
    id: "demo-o4",
    code: `GAE-${now.getFullYear()}-0004`,
    customer_id: "demo-c3",
    product: "pet_personalizado",
    project_name: "Miniatura da Nina",
    quantity: 1,
    dimensions: "12 cm",
    material: "Resina",
    colors: "Pintura realista",
    finishing: "Verniz acetinado",
    purpose: "Presente",
    event_date: iso(9),
    due_date: iso(1),
    status: "bloqueado",
    priority: "critica",
    urgency_reason: "Presente de aniversário com data fixa.",
    blocked_reason: "Fotos do pet em baixa resolução; aguardando novas imagens.",
    owner_id: null,
    printer_id: null,
    estimated_hours: 12,
    estimated_material: "300 ml resina",
    internal_notes: "Pedir fotos laterais.",
    commercial_notes: "Cliente ansioso, responder rápido.",
    briefing: "Miniatura fiel do cachorro, pose sentada.",
    references_notes: "5 fotos enviadas (baixa qualidade).",
    rights_notes: "Não aplicável.",
    briefing_complete: false,
    value: 890,
    down_payment: 445,
    payment_status: "entrada_paga",
    approval_registered: false,
    approval_date: null,
    approval_version: "v1",
    approval_notes: null,
    created_at: iso(-9),
    updated_at: iso(-1),
  },
  {
    ...orderBase,
    id: "demo-o5",
    code: `GAE-${now.getFullYear()}-0005`,
    customer_id: "demo-c1",
    product: "peca_personalizada",
    project_name: "Suporte de display Nortex",
    quantity: 8,
    dimensions: "15 x 10 cm",
    material: "PETG",
    colors: "Preto",
    finishing: "Lixado",
    purpose: "Stand de feira",
    event_date: iso(5),
    due_date: iso(4),
    status: "fila_impressao",
    priority: "alta",
    owner_id: "demo-t1",
    printer_id: "demo-p1",
    estimated_hours: 10,
    estimated_material: "600 g PETG",
    internal_notes: "Imprimir junto com os chaveiros.",
    commercial_notes: "Incluso no mesmo contrato do mascote.",
    briefing: "Suporte inclinado para tablet.",
    references_notes: "Desenho técnico enviado.",
    rights_notes: "Não aplicável.",
    value: 1200,
    down_payment: 600,
    payment_status: "entrada_paga",
    approval_registered: true,
    approval_date: iso(-3),
    approval_version: "v1",
    approval_notes: "Aprovado em reunião.",
    created_at: iso(-12),
    updated_at: iso(-1),
  },
  {
    ...orderBase,
    id: "demo-o6",
    code: `GAE-${now.getFullYear()}-0006`,
    customer_id: "demo-c2",
    product: "trofeu",
    project_name: "Placa comemorativa",
    quantity: 4,
    dimensions: "18 cm",
    material: "PLA",
    colors: "Prata",
    finishing: "Pintura metálica",
    purpose: "Homenagem",
    event_date: null,
    due_date: iso(-6),
    status: "concluido",
    priority: "normal",
    owner_id: "demo-t2",
    printer_id: "demo-p2",
    estimated_hours: 8,
    estimated_material: "400 g PLA",
    internal_notes: "Entregue no prazo.",
    commercial_notes: "Cliente satisfeito.",
    briefing: "Placa com nomes gravados.",
    references_notes: "Lista de nomes enviada.",
    rights_notes: "Não aplicável.",
    value: 1600,
    down_payment: 1600,
    payment_status: "pago",
    approval_registered: true,
    approval_date: iso(-15),
    approval_version: "v1",
    approval_notes: "Aprovado.",
    created_at: iso(-40),
    updated_at: iso(-6),
  },
  {
    ...orderBase,
    id: "demo-o7",
    code: `GAE-${now.getFullYear()}-0007`,
    customer_id: "demo-c4",
    product: "mascote_corporativo",
    project_name: "Mascote Vertice mini",
    quantity: 30,
    dimensions: "10 cm",
    material: "PLA",
    colors: "Multicor",
    finishing: "Sem pintura",
    purpose: "Kit de boas-vindas",
    event_date: null,
    due_date: iso(12),
    status: "recebido",
    priority: "normal",
    owner_id: null,
    printer_id: null,
    estimated_hours: 30,
    estimated_material: "1,8 kg PLA",
    internal_notes: null,
    commercial_notes: "Proposta aprovada, briefing em coleta.",
    briefing: "Versão reduzida do mascote existente.",
    references_notes: null,
    rights_notes: "Marca do cliente.",
    briefing_complete: false,
    value: 5400,
    down_payment: 0,
    payment_status: "pendente",
    approval_registered: false,
    approval_date: null,
    approval_version: null,
    approval_notes: null,
    created_at: iso(-3),
    updated_at: iso(-1),
  },
  {
    ...orderBase,
    id: "demo-o8",
    code: `GAE-${now.getFullYear()}-0008`,
    customer_id: "demo-c3",
    product: "peca_personalizada",
    project_name: "Peça de reposição",
    quantity: 3,
    dimensions: "6 cm",
    material: "PETG",
    colors: "Preto",
    finishing: "Bruto",
    purpose: "Manutenção",
    event_date: null,
    due_date: iso(2),
    status: "acabamento",
    priority: "alta",
    owner_id: "demo-t2",
    printer_id: "demo-p2",
    estimated_hours: 4,
    estimated_material: "120 g PETG",
    internal_notes: "Verificar encaixe.",
    commercial_notes: null,
    briefing: "Cópia da peça enviada pelo cliente.",
    references_notes: "Medidas por paquímetro.",
    rights_notes: "Não aplicável.",
    value: 420,
    down_payment: 420,
    payment_status: "pago",
    approval_registered: true,
    approval_date: iso(-4),
    approval_version: "v1",
    approval_notes: "Aprovado por WhatsApp.",
    created_at: iso(-8),
    updated_at: iso(0),
  },
];

export const demoOrderItems: OrderItem[] = [
  {
    id: "demo-i1",
    order_id: "demo-o3",
    description: "Chaveiro logotipo",
    quantity: 250,
    dimensions: "5 cm",
    material: "PLA",
    colors: "Branco/vermelho",
    finishing: "Sem pintura",
    ...base(-30),
  },
];

export const demoOrderFiles: OrderFile[] = [
  {
    id: "demo-f1",
    order_id: "demo-o1",
    name: "referencia-mascote.png",
    size: 842_000,
    mime_type: "image/png",
    category: "referencia",
    url: null,
    ...base(-14),
  },
  {
    id: "demo-f2",
    order_id: "demo-o1",
    name: "briefing-nortex.pdf",
    size: 220_500,
    mime_type: "application/pdf",
    category: "documento",
    url: null,
    ...base(-14),
  },
  {
    id: "demo-f3",
    order_id: "demo-o3",
    name: "chaveiro-final.stl",
    size: 5_400_000,
    mime_type: "model/stl",
    category: "modelo",
    url: null,
    ...base(-25),
  },
];

export const demoApprovals: Approval[] = [
  {
    id: "demo-a1",
    order_id: "demo-o2",
    status: "pendente",
    version: "v2",
    approved_at: null,
    notes: "Enviado ao cliente há 2 dias.",
    ...base(-4),
  },
  {
    id: "demo-a2",
    order_id: "demo-o3",
    status: "aprovado",
    version: "v1",
    approved_at: iso(-5),
    notes: "Aprovado por e-mail.",
    ...base(-6),
  },
];

export const demoJobs: ProductionJob[] = [
  {
    id: "demo-j1",
    order_id: "demo-o3",
    printer_id: "demo-p1",
    member_id: "demo-t2",
    stage: "imprimindo",
    estimated_hours: 40,
    real_hours: 22,
    estimated_material: "2,5 kg PLA",
    real_material: "1,4 kg PLA",
    failed: false,
    failure_reason: null,
    reprint: false,
    notes: "Lote 3 de 5 em andamento.",
    started_at: iso(-2),
    finished_at: null,
    ...base(-3),
  },
  {
    id: "demo-j2",
    order_id: "demo-o8",
    printer_id: "demo-p2",
    member_id: "demo-t2",
    stage: "acabamento",
    estimated_hours: 4,
    real_hours: 3,
    estimated_material: "120 g PETG",
    real_material: "130 g PETG",
    failed: true,
    failure_reason: "Warping na primeira tentativa.",
    reprint: true,
    notes: "Reimpressão concluída.",
    started_at: iso(-2),
    finished_at: iso(-1),
    ...base(-3),
  },
];

export const demoEvents: ProductionEvent[] = [
  {
    id: "demo-e1",
    order_id: "demo-o3",
    job_id: "demo-j1",
    author: "Paula Nunes",
    message: "Lote 3 iniciado na Snapmaker U1.",
    ...base(0),
  },
  {
    id: "demo-e2",
    order_id: "demo-o4",
    job_id: null,
    author: "Renan Souza",
    message: "Pedido bloqueado: aguardando novas fotos do pet.",
    ...base(-1),
  },
];

export const demoAudit: AuditLog[] = [
  {
    id: "demo-l1",
    entity: "orders",
    entity_id: "demo-o3",
    field: "status",
    old_value: "Na fila de impressão",
    new_value: "Imprimindo",
    author: "Paula Nunes",
    comment: "Início do lote 3.",
    ...base(0),
  },
  {
    id: "demo-l2",
    entity: "orders",
    entity_id: "demo-o2",
    field: "prioridade",
    old_value: "Alta",
    new_value: "Urgente",
    author: "Caio Ferraz",
    comment: "Evento com data fixa.",
    ...base(-2),
  },
];
