/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ImpressorasRouteImport } from './routes/impressoras'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as ClientesIndexRouteImport } from './routes/clientes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes/$id'
import { Route as ComercialAcoesRouteImport } from './routes/comercial.acoes'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as PedidosIdRouteImport } from './routes/pedidos/$id'
import { Route as PedidosKanbanRouteImport } from './routes/pedidos/kanban'
import { Route as PedidosNovoRouteImport } from './routes/pedidos/novo'
import { Route as ComercialAcoesIndexRouteImport } from './routes/comercial.acoes.index'
import { Route as ComercialAcoesIdRouteImport } from './routes/comercial.acoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressorasRoute = ImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialAcoesRoute = ComercialAcoesRouteImport.update({
  id: '/comercial/acoes',
  path: '/comercial/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosKanbanRoute = PedidosKanbanRouteImport.update({
  id: '/pedidos/kanban',
  path: '/pedidos/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialAcoesIndexRoute = ComercialAcoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComercialAcoesRoute,
} as any)
const ComercialAcoesIdRoute = ComercialAcoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComercialAcoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/impressoras': typeof ImpressorasRoute
  '/producao': typeof ProducaoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/acoes': typeof ComercialAcoesRouteWithChildren
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/kanban': typeof PedidosKanbanRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/comercial/acoes/$id': typeof ComercialAcoesIdRoute
  '/comercial/acoes/': typeof ComercialAcoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/impressoras': typeof ImpressorasRoute
  '/producao': typeof ProducaoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/kanban': typeof PedidosKanbanRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/comercial/acoes/$id': typeof ComercialAcoesIdRoute
  '/comercial/acoes': typeof ComercialAcoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe': typeof EquipeRoute
  '/impressoras': typeof ImpressorasRoute
  '/producao': typeof ProducaoRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/comercial/acoes': typeof ComercialAcoesRouteWithChildren
  '/pedidos/$id': typeof PedidosIdRoute
  '/pedidos/kanban': typeof PedidosKanbanRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/comercial/acoes/$id': typeof ComercialAcoesIdRoute
  '/comercial/acoes/': typeof ComercialAcoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/equipe'
    | '/impressoras'
    | '/producao'
    | '/clientes/$id'
    | '/comercial/acoes'
    | '/pedidos/$id'
    | '/pedidos/kanban'
    | '/pedidos/novo'
    | '/clientes/'
    | '/pedidos/'
    | '/comercial/acoes/$id'
    | '/comercial/acoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/equipe'
    | '/impressoras'
    | '/producao'
    | '/clientes/$id'
    | '/pedidos/$id'
    | '/pedidos/kanban'
    | '/pedidos/novo'
    | '/clientes'
    | '/pedidos'
    | '/comercial/acoes/$id'
    | '/comercial/acoes'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/equipe'
    | '/impressoras'
    | '/producao'
    | '/clientes/$id'
    | '/comercial/acoes'
    | '/pedidos/$id'
    | '/pedidos/kanban'
    | '/pedidos/novo'
    | '/clientes/'
    | '/pedidos/'
    | '/comercial/acoes/$id'
    | '/comercial/acoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EquipeRoute: typeof EquipeRoute
  ImpressorasRoute: typeof ImpressorasRoute
  ProducaoRoute: typeof ProducaoRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ComercialAcoesRoute: typeof ComercialAcoesRouteWithChildren
  PedidosIdRoute: typeof PedidosIdRoute
  PedidosKanbanRoute: typeof PedidosKanbanRoute
  PedidosNovoRoute: typeof PedidosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressoras': {
      id: '/impressoras'
      path: '/impressoras'
      fullPath: '/impressoras'
      preLoaderRoute: typeof ImpressorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/acoes': {
      id: '/comercial/acoes'
      path: '/comercial/acoes'
      fullPath: '/comercial/acoes'
      preLoaderRoute: typeof ComercialAcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/kanban': {
      id: '/pedidos/kanban'
      path: '/pedidos/kanban'
      fullPath: '/pedidos/kanban'
      preLoaderRoute: typeof PedidosKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/acoes/': {
      id: '/comercial/acoes/'
      path: '/'
      fullPath: '/comercial/acoes/'
      preLoaderRoute: typeof ComercialAcoesIndexRouteImport
      parentRoute: typeof ComercialAcoesRoute
    }
    '/comercial/acoes/$id': {
      id: '/comercial/acoes/$id'
      path: '/$id'
      fullPath: '/comercial/acoes/$id'
      preLoaderRoute: typeof ComercialAcoesIdRouteImport
      parentRoute: typeof ComercialAcoesRoute
    }
  }
}

interface ComercialAcoesRouteChildren {
  ComercialAcoesIdRoute: typeof ComercialAcoesIdRoute
  ComercialAcoesIndexRoute: typeof ComercialAcoesIndexRoute
}

const ComercialAcoesRouteChildren: ComercialAcoesRouteChildren = {
  ComercialAcoesIdRoute: ComercialAcoesIdRoute,
  ComercialAcoesIndexRoute: ComercialAcoesIndexRoute,
}

const ComercialAcoesRouteWithChildren = ComercialAcoesRoute._addFileChildren(
  ComercialAcoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EquipeRoute: EquipeRoute,
  ImpressorasRoute: ImpressorasRoute,
  ProducaoRoute: ProducaoRoute,
  ClientesIdRoute: ClientesIdRoute,
  ComercialAcoesRoute: ComercialAcoesRouteWithChildren,
  PedidosIdRoute: PedidosIdRoute,
  PedidosKanbanRoute: PedidosKanbanRoute,
  PedidosNovoRoute: PedidosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
